### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project delta-ui-common: There are test failures.

### ISSUE THREAD

**Issue by bwakkie** [AtlasOfLivingAustralia/open-delta#256]
Hi,

I could not compile the latest source of open-delta 1.0.3 snapshot the 'normal' way....
java version oracle-jdk-bin 1.8.0.131
maven version 3.2.5(3.2)and 3.3.9
junit version 3.8.2-r1 and 4.12-r1
...on a gentoo box.

By disabling the maven test during compile like so ...
#mvn clean install -X -Dmaven.test.skip=true 
... all compiled well. But still ... I guess the maven test has a purpose no?

Below the error that occured by issuing the standard compile command...
#mvn clean install

-------------------------------------------------------                                            
 T E S T S                                                                                         
-------------------------------------------------------                                            
Running au.org.ala.delta.ui.image.overlay.TextOverlayLocationTest                                  
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 sec                          
Running au.org.ala.delta.ui.image.overlay.OverlayTextBuilderTest                                   
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec                          
Running au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest                                             
Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE!             
testReadSimpleFormattedDocument(au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.awt.HeadlessException                                                                         
        at sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:226)                   
        at au.org.ala.delta.util.Utils.adjustFontSize(Utils.java:940)                              
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler$FontSizeAttributeHandler.handleAttribute(DocumentBuildingRtfHandler.java:411)
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler.handleAttributeChanges(DocumentBuildingRtfHandler.java:211)
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler.onCharacterAttributeChange(DocumentBuildingRtfHandler.java:178)
        at au.org.ala.delta.rtf.RTFReader.translateKeyword(RTFReader.java:285)                     
        at au.org.ala.delta.rtf.RTFReader.parseRtfKeyword(RTFReader.java:185)                                                                                  
        at au.org.ala.delta.rtf.RTFReader.parse(RTFReader.java:79)                                                                                             
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKit.parseRtf(SimpleRtfEditorKit.java:103)        
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKit.read(SimpleRtfEditorKit.java:91)             
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest.testReadSimpleFormattedDocument(SimpleRtfEditorKitTest.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                             
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                       
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)                                        
        at junit.framework.TestCase.runTest(TestCase.java:168)                                     
        at junit.framework.TestCase.runBare(TestCase.java:134)                                                                                                 
        at junit.framework.TestResult$1.protect(TestResult.java:110)                                                                                           
        at junit.framework.TestResult.runProtected(TestResult.java:128)                                                                                        
        at junit.framework.TestResult.run(TestResult.java:113)                                     
        at junit.framework.TestCase.run(TestCase.java:124)                                         
        at junit.framework.TestSuite.runTest(TestSuite.java:243)                                   
        at junit.framework.TestSuite.run(TestSuite.java:238)                                       
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)           
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)                                                                    
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) 
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)         
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                             
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)           
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   
        at java.lang.reflect.Method.invoke(Method.java:498)                                        
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)                                   
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)                                  
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) 
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)                

testMoreComplexDocument(au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest)  Time elapsed: 0.001 sec  <<< ERROR!                                
java.awt.HeadlessException                       
        at sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:226)                   
        at au.org.ala.delta.util.Utils.adjustFontSize(Utils.java:940)                              
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler$FontSizeAttributeHandler.handleAttribute(DocumentBuildingRtfHandler.java:411) 
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler.handleAttributeChanges(DocumentBuildingRtfHandler.java:211)                   
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler.onCharacterAttributeChange(DocumentBuildingRtfHandler.java:178)               
        at au.org.ala.delta.rtf.RTFReader.translateKeyword(RTFReader.java:285)                     
        at au.org.ala.delta.rtf.RTFReader.parseRtfKeyword(RTFReader.java:185)                      
        at au.org.ala.delta.rtf.RTFReader.parse(RTFReader.java:79)                                 
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKit.parseRtf(SimpleRtfEditorKit.java:103)        
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKit.read(SimpleRtfEditorKit.java:91)             
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest.testMoreComplexDocument(SimpleRtfEditorKitTest.java:83)                           
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                             
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)           
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   
        at java.lang.reflect.Method.invoke(Method.java:498)                                        
        at junit.framework.TestCase.runTest(TestCase.java:168)                                     
        at junit.framework.TestCase.runBare(TestCase.java:134)                                     
        at junit.framework.TestResult$1.protect(TestResult.java:110)                               
        at junit.framework.TestResult.runProtected(TestResult.java:128)                            
        at junit.framework.TestResult.run(TestResult.java:113)                                     
        at junit.framework.TestCase.run(TestCase.java:124)                                         
        at junit.framework.TestSuite.runTest(TestSuite.java:243)                                   
        at junit.framework.TestSuite.run(TestSuite.java:238)                                       
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)           
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)        
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) 
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)         
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                             
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)           
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   
        at java.lang.reflect.Method.invoke(Method.java:498)                                        
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)                                   
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)                                  
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) 
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)                

testReadSimpleDocument(au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest)  Time elapsed: 0.003 sec  <<< ERROR!                                 
java.awt.HeadlessException                       
        at sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:226)                   
        at au.org.ala.delta.util.Utils.adjustFontSize(Utils.java:940)                              
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler$FontSizeAttributeHandler.handleAttribute(DocumentBuildingRtfHandler.java:411) 
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler.handleAttributeChanges(DocumentBuildingRtfHandler.java:211)                   
        at au.org.ala.delta.ui.rtf.DocumentBuildingRtfHandler.onCharacterAttributeChange(DocumentBuildingRtfHandler.java:178)               
        at au.org.ala.delta.rtf.RTFReader.translateKeyword(RTFReader.java:285)                     
        at au.org.ala.delta.rtf.RTFReader.parseRtfKeyword(RTFReader.java:185)                      
        at au.org.ala.delta.rtf.RTFReader.parse(RTFReader.java:79)                                 
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKit.parseRtf(SimpleRtfEditorKit.java:103)        
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKit.read(SimpleRtfEditorKit.java:91)             
        at au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest.testReadSimpleDocument(SimpleRtfEditorKitTest.java:46)                            
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                             
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)           
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   
        at java.lang.reflect.Method.invoke(Method.java:498)                                        
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)                                                     
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)                                                    
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) 
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)                

Results :                                        

Tests in error:                                  
  testReadSimpleFormattedDocument(au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest)                  
  testMoreComplexDocument(au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest)                          
  testReadSimpleDocument(au.org.ala.delta.ui.rtf.SimpleRtfEditorKitTest)                           

Tests run: 12, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------                    
[INFO] Reactor Summary:                          
[INFO]                                           
[INFO] DELTA Common ....................................... SUCCESS [  5.140 s]                    
[INFO] DELTA User Interface Common ........................ FAILURE [  1.897 s]                    
[INFO] DIST ............................................... SKIPPED                                
[INFO] KEY ................................................ SKIPPED                                
[INFO] intkey ............................................. SKIPPED                                
[INFO] DELTA Editor ....................................... SKIPPED                                
[INFO] CONFOR ............................................. SKIPPED                                
[INFO] DELFOR ............................................. SKIPPED                                
[INFO] Open DELTA suite ................................... SKIPPED                                
[INFO] ------------------------------------------------------------------------                    
[INFO] BUILD FAILURE                             
[INFO] ------------------------------------------------------------------------                    
[INFO] Total time: 7.220 s                       
[INFO] Finished at: 2017-06-25T13:28:41+02:00    
[INFO] Final Memory: 34M/380M                    
[INFO] ------------------------------------------------------------------------                    
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project delta-ui-common: There are test failures. 
[ERROR]                                          
[ERROR] Please refer to /home/bastiaan/backup/source/git/open-delta/ui-common/target/surefire-reports for the individual test results.                        
[ERROR] -> [Help 1]                              
[ERROR]                                          
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                
[ERROR] Re-run Maven using the -X switch to enable full debug logging.                             
[ERROR]                                          
[ERROR] For more information about the errors and possible solutions, please read the following articles:                                                     
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException             
[ERROR]                                          
[ERROR] After correcting the problems, you can resume the build with the command                   
[ERROR]   mvn <goals> -rf :delta-ui-common

**Comment by starsareintherose** [comment]
I think now it's okay, I patched some
